In [1]:
# define root path of project 
from pathlib import Path
import sys

ROOT = Path("..").resolve()
sys.path.append(str(ROOT))

# load general setup
from utils.setup_general import *

Setup general cargado

# Importar funciones

In [2]:
from engines.e1001_processs_UPRA import run as run_1001_processs_UPRA
from engines.e2001_descargar_poligonostitulosmineros import run as run_2001_descargar_poligonostitulosmineros

Setup GIS cargado

# Ejecutar funciones

In [2]:
run_1001_processs_UPRA()

--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
1001 Procesar UPRA-EVA
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------
--------------------------------

-------------------------------- UPRA 2019-2024

,Código Dane departamento,Departamento,Código Dane municipio,Municipio,Desagregación cultivo,Cultivo,Ciclo del cultivo,Grupo cultivo,Subgrupo,Año,Periodo,Área sembrada (ha),Área cosechada (ha),Producción (t),Rendimiento (t/ha),Nombre científico del cultivo,Código del cultivo,Estado físico del cultivo
0,5,Antioquia,05001,Medellín,Aguacate demás variedades,Aguacate,Permanente,Frutales,Demás frutales,2019,2019,24.00,23.00,138.00,6.00,Persea americana,2040299,En fresco
1,5,Antioquia,05001,Medellín,Aguacate demás variedades,Aguacate,Permanente,Frutales,Demás frutales,2020,2020,8.52,3.52,21.12,6.00,Persea americana,2040299,En fresco
2,5,Antioquia,05001,Medellín,Aguacate demás variedades,Aguacate,Permanente,Frutales,Demás frutales,2021,2021,8.52,4.52,27.12,6.00,Persea americana,2040299,En fresco

-------------------------------- UPRA 2007-2018

,CÓD. \nDEP.,DEPARTAMENTO,CÓD. MUN.,MUNICIPIO,GRUPO \nDE CULTIVO,SUBGRUPO \nDE CULTIVO,CULTIVO,DESAGREGACIÓN REGIONAL Y/O SISTEMA PRODUCTIVO,AÑO,PERIODO,Área Sembrada\n(ha),Área Cosechada\n(ha),Producción\n(t),Rendimiento\n(t/ha),ESTADO FISICO PRODUCCION,NOMBRE \nCIENTIFICO,CICLO DE CULTIVO,Unnamed: 17
0,15,BOYACA,15114,BUSBANZA,HORTALIZAS,ACELGA,ACELGA,ACELGA,2006,2006B,2.00,1.00,1.00,1.00,FRUTO FRESCO,BETA VULGARIS,TRANSITORIO,NaN
1,25,CUNDINAMARCA,25754,SOACHA,HORTALIZAS,ACELGA,ACELGA,ACELGA,2006,2006B,82.00,80.00,"1,440.00",18.00,FRUTO FRESCO,BETA VULGARIS,TRANSITORIO,NaN
2,25,CUNDINAMARCA,25214,COTA,HORTALIZAS,ACELGA,ACELGA,ACELGA,2006,2006B,1.50,1.50,26.00,17.33,FRUTO FRESCO,BETA VULGARIS,TRANSITORIO,NaN

--------------------------------
Archivo de clasificación armonizada

,ciclo_original,grupo_original,cultivo_original,area_sembrada_ha,año,fuente_taxonomia,ciclo_armonizado,grupo_armonizado,cultivo_armonizado,notas,Armonizado,porcentaje acumulado armonizado 2018,porcentaje acumulado armonizado 2019
0,PERMANENTE,OTROS PERMANENTES,CAFE,"10,940,392.32",2007-2018,Eva antiguo,Permanente,Cultivos tropicales tradicionales,Café,NaN,True,0.18,0.00
1,TRANSITORIO,CEREALES,MAIZ,"7,606,746.69",2007-2018,Eva antiguo,Transitorio,Cereales,Maíz,NaN,True,0.31,0.00

--------------------------------
Porcentaje de area sembrada que se logró armonizar

                                          0
porcentaje acumulado armonizado  2018 98.83
porcentaje acumulado armonizado  2019 99.98

-------------------------------- UPRA-2007-2018
Explorar duplicados por cultivo_original en la lista armonizada. En los siguientes datos, las filas duplicadas deben ser idénticas en todas las columnas

       cultivo_original ciclo_armonizado                                   grupo_armonizado  cultivo_armonizado
54                  AJI      Transitorio                                         Hortalizas                 Ají
142                 AJI      Transitorio                                         Hortalizas                 Ají
178            ALBAHACA       Permanente  Cultivos para condimentos, bebidas medicinales...            Albahaca
138            ALBAHACA       Permanente  Cultivos para condimentos, bebidas medicinales...            Albahaca
218             CURCUMA       Permanente                                Raíces y tubérculos   Cúrcuma o azafrán
160             CURCUMA       Permanente                                Raíces y tubérculos   Cúrcuma o azafrán
177           ESPARRAGO      Transitorio                                         Hortalizas           Espárrago
119           ESPARRAGO      Transitorio                                         Hortalizas           Espárrago
191             OREGANO       Permanente  Cultivos para condimentos, bebidas medicinales...             Orégano
215             OREGANO       Permanente  Cultivos para condimentos, bebidas medicinales...             Orégano
145             PEREJIL      Transitorio  Cultivos para condimentos, bebidas medicinales...             Perejil
239             PEREJIL      Transitorio  Cultivos para condimentos, bebidas medicinales...             Perejil
121  PLANTAS AROMATICAS      Transitorio  Cultivos para condimentos, bebidas medicinales...  Plantas aromáticas
108  PLANTAS AROMATICAS      Transitorio  Cultivos para condimentos, bebidas medicinales...  Plantas aromáticas
211              ROMERO       Permanente  Cultivos para condimentos, bebidas medicinales...              Romero
222              ROMERO       Permanente  Cultivos para condimentos, bebidas medicinales...              Romero
179                RUDA       Permanente  Cultivos para condimentos, bebidas medicinales...                Ruda
199                RUDA       Permanente  Cultivos para condimentos, bebidas medicinales...                Ruda
149             TOMILLO       Permanente  Cultivos para condimentos, bebidas medicinales...             Tomillo
223             TOMILLO       Permanente  Cultivos para condimentos, bebidas medicinales...             Tomillo

-------------------------------- UPRA-2019-2024
Explorar duplicados por cultivo_original en la lista armonizada. En los siguientes datos, las filas duplicadas deben ser idénticas en todas las columnas
Este arreglo debería estar vacío.

Empty DataFrame
Columns: [cultivo_original, ciclo_armonizado, grupo_armonizado, cultivo_armonizado]
Index: []

-------------------------------- UPRA 2007-2018: Resumen de todos los valores ANTES de armonizar

       Área Sembrada\n(ha)  Área Cosechada\n(ha)  Producción\n(t)  Rendimiento\n(t/ha)
sum          60,334,863.76         51,807,216.06   573,927,302.13         1,919,060.51
count           210,847.00            210,847.00       210,847.00           207,289.00

-------------------------------- UPRA 2007-2018: Resumen de todos los valores DESPUES de armonizar

       Área Sembrada\n(ha)  Área Cosechada\n(ha)  Producción\n(t)  Rendimiento\n(t/ha)
sum          59,627,601.62         51,524,887.31   571,988,858.77         1,893,706.02
count           207,389.00            207,389.00       207,389.00           204,336.00

-------------------------------- UPRA 2007-2018: Porcentaje de magnitudes que se conservan: despues / antes

       Área Sembrada\n(ha)  Área Cosechada\n(ha)  Producción\n(t)  Rendimiento\n(t/ha)
sum                  98.83                 99.46            99.66                98.68
count                98.36                 98.36            98.36                98.58

-------------------------------- UPRA 2019-2024: Resumen de todos los valores ANTES de armonizar

       Área sembrada (ha)  Área cosechada (ha)  Producción (t)  Rendimiento (t/ha)
sum         32,491,336.82        29,707,563.72  450,336,864.70        1,495,042.11
count          141,073.00           141,073.00      141,073.00          141,073.00

-------------------------------- UPRA 2019-2024: Resumen de todos los valores DESPUES de armonizar

       Área sembrada (ha)  Área cosechada (ha)  Producción (t)  Rendimiento (t/ha)
sum         32,484,957.56        29,701,729.43  450,303,360.63        1,494,265.79
count          140,924.00           140,924.00      140,924.00          140,924.00

-------------------------------- UPRA 2019-2024: Porcentaje de magnitudes que se conservan: despues / antes

       Área sembrada (ha)  Área cosechada (ha)  Producción (t)  Rendimiento (t/ha)
sum                 99.98                99.98           99.99               99.95
count               99.89                99.89           99.89               99.89

--------------------------------  Tipo de datos en cada columna
<class 'pandas.core.frame.DataFrame'>
Index: 348313 entries, 0 to 140923
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   codigo_dane_municipio  348313 non-null  object
 1   anno                   348313 non-null  int32
 2   area_sembrada_ha       348313 non-null  float64
 3   area_cosechada_ha      348313 non-null  float64
 4   produccion_t           348313 non-null  float64
 5   rendimiento_t_ha       345260 non-null  float64
 6   ciclo_armonizado       348313 non-null  object
 7   grupo_armonizado       348313 non-null  object
 8   cultivo_armonizado     348313 non-null  object
dtypes: float64(4), int32(1), object(4)
memory usage: 25.2+ MB

None

--------------------------------  Estadísticas descriptivas de las columnas

            anno  area_sembrada_ha  area_cosechada_ha  produccion_t  rendimiento_t_ha
count 348,313.00        348,313.00         348,313.00    348,313.00        345,260.00
mean    2,016.24            264.45             233.20      2,934.98              9.81
std         5.33          1,150.49           1,031.04     46,207.89             15.20
min     2,006.00              0.00               0.00          0.00              0.00
25%     2,012.00              8.00               6.00         27.20              1.60
50%     2,017.00             28.41              24.00        124.70              5.67
75%     2,021.00            125.00             107.00        600.95             12.00
max     2,024.00         60,000.00          61,000.00  4,776,340.50            253.00

-------------------------------- Conteo de registros municipio-año por cultivo (20 primeros)

   cultivo_armonizado  area_sembrada_ha  area_cosechada_ha  produccion_t  rendimiento_t_ha
0                Maíz             44383              44383         44383             44334
1              Frijol             23572              23572         23572             23544
2                Yuca             17996              17996         17996             17970
3              Tomate             16159              16159         16159             16146
4             Plátano             13875              13875         13875             13840
5                Papa             12565              12565         12565             12559
6                Caña             12106              12106         12106             12062
7               Arroz             11796              11796         11796             11786
8                Café             11071              11071         11071             11035
9              Arveja             10418              10418         10418             10417
10              Cacao              9505               9505          9505              9163
11           Aguacate              9329               9329          9329              8933
12         Habichuela              5848               5848          5848              5845
13              Limón              5443               5443          5443              5366
14            Ahuyama              5372               5372          5372              5362
15               Lulo              5045               5045          5045              4953
16               Mora              5026               5026          5026              4979
17            Naranja              4949               4949          4949              4861
18    Tomate de árbol              4313               4313          4313              4246
19            Patilla              4067               4067          4067              4046

Los 20 primeros representan este porcentaje del total de registros

   area_sembrada_ha  area_cosechada_ha  produccion_t  rendimiento_t_ha
0              0.67               0.67          0.67              0.67

-------------------------------- Suma de magnitudes por cultivo (20 primeros)

   cultivo_armonizado  area_sembrada_ha  area_cosechada_ha   produccion_t  rendimiento_t_ha
0                Café     16,014,408.67      13,243,603.24  13,777,349.88         10,591.34
1               Arroz     10,919,929.20      10,538,874.04  55,514,666.38         47,780.64
2                Maíz     10,879,069.82       9,929,695.07  26,602,119.56         92,168.00
3     Palma de aceite     10,039,306.77       8,280,409.53  27,746,724.47          6,520.68
4                Caña      8,813,477.41       7,706,420.37 554,662,871.09        328,268.14
5             Plátano      8,090,460.17       7,304,411.01  67,250,703.16        104,052.78
6                Yuca      3,925,707.70       3,440,897.51  38,257,996.01        187,150.62
7               Cacao      3,737,506.47       3,080,839.26   1,690,960.48          5,165.48
8                Papa      3,335,073.71       3,145,661.95  63,296,949.28        198,263.06
9              Frijol      2,236,306.01       2,067,940.33   2,690,921.82         28,746.01
10             Banano      1,605,848.52       1,515,366.94  38,715,786.44         41,452.22
11           Aguacate      1,278,630.06         964,007.36   9,349,739.81         74,176.50
12               Soya        909,979.22         923,455.21   2,316,622.97          1,615.06
13               Ñame        659,277.48         584,796.00   6,653,667.01         25,579.16
14              Mango        567,668.02         483,096.22   5,181,406.15         37,440.09
15     Otros cítricos        562,628.04         487,481.15   7,955,686.27         40,923.03
16             Arveja        559,331.11         520,396.17   1,124,482.70         17,666.48
17            Naranja        480,650.65         429,750.47   6,661,117.15         57,844.72
18            Algodón        465,366.06         449,667.39     941,181.53          2,539.34
19               Piña        409,981.02         311,347.27  12,544,168.80         97,403.48

Los 20 primeros representan este porcentaje del total de registros

   area_sembrada_ha  area_cosechada_ha  produccion_t  rendimiento_t_ha
0              0.93               0.93          0.92              0.41

-------------------------------- 20 cultivos con más observaciones de area sembrada:
 ['Maíz', 'Frijol', 'Yuca', 'Tomate', 'Plátano', 'Papa', 'Caña', 'Arroz', 'Café', 'Arveja', 'Cacao', 'Aguacate', 'Habichuela', 'Limón', 'Ahuyama', 'Lulo', 'Mora', 'Naranja', 'Tomate de árbol', 'Patilla', 'Mango']

-------------------------------- 20 cultivos con mayor magnitud de area sembrada:
 ['Café', 'Arroz', 'Maíz', 'Palma de aceite', 'Caña', 'Plátano', 'Yuca', 'Cacao', 'Papa', 'Frijol', 'Banano', 'Aguacate', 'Soya', 'Ñame', 'Mango', 'Otros cítricos', 'Arveja', 'Naranja', 'Algodón', 'Piña', 'Coco']

-------------------------------- Cultivos principales por número de registros y area sembrada. N = 29
 ['Café', 'Arroz', 'Maíz', 'Palma de aceite', 'Caña', 'Plátano', 'Yuca', 'Cacao', 'Papa', 'Frijol', 'Banano', 'Aguacate', 'Soya', 'Ñame', 'Mango', 'Otros cítricos', 'Arveja', 'Naranja', 'Algodón', 'Piña', 'Coco', 'Tomate', 'Habichuela', 'Limón', 'Ahuyama', 'Lulo', 'Mora', 'Tomate de árbol', 'Patilla']

  0%|                                                                                           | 0/29 [00:00<?, ?it/s]

--------------------------------  Procesando:  Café

  3%|██▊                                                                                | 1/29 [00:00<00:16,  1.68it/s]

--------------------------------  Procesando:  Arroz

  7%|█████▋                                                                             | 2/29 [00:01<00:16,  1.61it/s]

--------------------------------  Procesando:  Maíz

 10%|████████▌                                                                          | 3/29 [00:01<00:17,  1.52it/s]

--------------------------------  Procesando:  Palma de aceite

 14%|███████████▍                                                                       | 4/29 [00:02<00:16,  1.49it/s]

--------------------------------  Procesando:  Caña

 17%|██████████████▎                                                                    | 5/29 [00:03<00:16,  1.42it/s]

--------------------------------  Procesando:  Plátano

 21%|█████████████████▏                                                                 | 6/29 [00:04<00:16,  1.39it/s]

--------------------------------  Procesando:  Yuca

 24%|████████████████████                                                               | 7/29 [00:04<00:16,  1.35it/s]

--------------------------------  Procesando:  Cacao

 28%|██████████████████████▉                                                            | 8/29 [00:05<00:16,  1.30it/s]

--------------------------------  Procesando:  Papa

 31%|█████████████████████████▊                                                         | 9/29 [00:06<00:15,  1.26it/s]

--------------------------------  Procesando:  Frijol

 34%|████████████████████████████▎                                                     | 10/29 [00:07<00:15,  1.19it/s]

--------------------------------  Procesando:  Banano

 38%|███████████████████████████████                                                   | 11/29 [00:08<00:15,  1.16it/s]

--------------------------------  Procesando:  Aguacate

 41%|█████████████████████████████████▉                                                | 12/29 [00:09<00:15,  1.13it/s]

--------------------------------  Procesando:  Soya

 45%|████████████████████████████████████▊                                             | 13/29 [00:10<00:14,  1.10it/s]

--------------------------------  Procesando:  Ñame

 48%|███████████████████████████████████████▌                                          | 14/29 [00:11<00:13,  1.08it/s]

--------------------------------  Procesando:  Mango

 52%|██████████████████████████████████████████▍                                       | 15/29 [00:12<00:13,  1.05it/s]

--------------------------------  Procesando:  Otros cítricos

 55%|█████████████████████████████████████████████▏                                    | 16/29 [00:13<00:12,  1.01it/s]

--------------------------------  Procesando:  Arveja

 59%|████████████████████████████████████████████████                                  | 17/29 [00:14<00:12,  1.02s/it]

--------------------------------  Procesando:  Naranja

 62%|██████████████████████████████████████████████████▉                               | 18/29 [00:15<00:11,  1.06s/it]

--------------------------------  Procesando:  Algodón

 66%|█████████████████████████████████████████████████████▋                            | 19/29 [00:16<00:11,  1.13s/it]

--------------------------------  Procesando:  Piña

 69%|████████████████████████████████████████████████████████▌                         | 20/29 [00:18<00:10,  1.18s/it]

--------------------------------  Procesando:  Coco

 72%|███████████████████████████████████████████████████████████▍                      | 21/29 [00:19<00:09,  1.22s/it]

--------------------------------  Procesando:  Tomate

 76%|██████████████████████████████████████████████████████████████▏                   | 22/29 [00:20<00:08,  1.25s/it]

--------------------------------  Procesando:  Habichuela

 79%|█████████████████████████████████████████████████████████████████                 | 23/29 [00:22<00:07,  1.31s/it]

--------------------------------  Procesando:  Limón

 83%|███████████████████████████████████████████████████████████████████▊              | 24/29 [00:23<00:06,  1.34s/it]

--------------------------------  Procesando:  Ahuyama

 86%|██████████████████████████████████████████████████████████████████████▋           | 25/29 [00:25<00:05,  1.41s/it]

--------------------------------  Procesando:  Lulo

 90%|█████████████████████████████████████████████████████████████████████████▌        | 26/29 [00:26<00:04,  1.43s/it]

--------------------------------  Procesando:  Mora

 93%|████████████████████████████████████████████████████████████████████████████▎     | 27/29 [00:28<00:02,  1.47s/it]

--------------------------------  Procesando:  Tomate de árbol

 97%|███████████████████████████████████████████████████████████████████████████████▏  | 28/29 [00:29<00:01,  1.50s/it]

--------------------------------  Procesando:  Patilla

100%|██████████████████████████████████████████████████████████████████████████████████| 29/29 [00:31<00:00,  1.09s/it]

-------------------------------- Estructura del panel final

,codigo_dane_municipio,anno,nombre_variable,variable_sujeto,variable_medicion,variable_detalle,variable_descripcion,valor,clasificacion_econometria
0,05101,2007,,Café,area_sembrada_ha,,Café: area_sembrada_ha de todos los tipos de Café,"9,680.00",Resultado
1,05034,2007,,Café,area_sembrada_ha,,Café: area_sembrada_ha de todos los tipos de Café,"8,696.00",Resultado
2,05642,2007,,Café,area_sembrada_ha,,Café: area_sembrada_ha de todos los tipos de Café,"6,011.00",Resultado
3,05209,2007,,Café,area_sembrada_ha,,Café: area_sembrada_ha de todos los tipos de Café,"5,578.00",Resultado
4,05091,2007,,Café,area_sembrada_ha,,Café: area_sembrada_ha de todos los tipos de Café,"5,439.40",Resultado
...,...,...,...,...,...,...,...,...,...
118486,99773,2022,,Patilla,produccion_t,Ciclo cultivo:Transitorio,Patilla: produccion_t de los demás cultivos - ...,"4,337.50",Control
118487,99773,2023,,Patilla,produccion_t,Ciclo cultivo:Permanente,Patilla: produccion_t de los demás cultivos - ...,"22,640.50",Control
118488,99773,2023,,Patilla,produccion_t,Ciclo cultivo:Transitorio,Patilla: produccion_t de los demás cultivos - ...,"4,375.20",Control
118489,99773,2024,,Patilla,produccion_t,Ciclo cultivo:Permanente,Patilla: produccion_t de los demás cultivos - ...,"23,536.00",Control
118490,99773,2024,,Patilla,produccion_t,Ciclo cultivo:Transitorio,Patilla: produccion_t de los demás cultivos - ...,"5,492.60",Control

-------------------------------- Mostrar mediciones disponibles

array(['Café: area_sembrada_ha de todos los tipos de Café',
       'Café: area_cosechada_ha de todos los tipos de Café',
       'Café: produccion_t de todos los tipos de Café',
       'Café: area_sembrada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Café: area_sembrada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Café: area_sembrada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Café: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Café: area_sembrada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Café: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Café: area_sembrada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Café: area_sembrada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Café: area_cosechada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Café: area_cosechada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Café: area_cosechada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Café: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Café: area_cosechada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Café: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Café: area_cosechada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Café: area_cosechada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Café: produccion_t de los demás cultivos - grupo de cultivos Hortalizas',
       'Café: produccion_t de los demás cultivos - grupo de cultivos Leguminosas',
       'Café: produccion_t de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Café: produccion_t de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Café: produccion_t de los demás cultivos - grupo de cultivos Frutales',
       'Café: produccion_t de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Café: produccion_t de los demás cultivos - grupo de cultivos Cereales',
       'Café: produccion_t de los demás cultivos - grupo de cultivos Oleaginosas',
       'Café: area_sembrada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Café: area_sembrada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Café: area_cosechada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Café: area_cosechada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Café: produccion_t de los demás cultivos - cultivos de ciclo Transitorio',
       'Café: produccion_t de los demás cultivos - cultivos de ciclo Permanente',
       'Arroz: area_sembrada_ha de todos los tipos de Arroz',
       'Arroz: area_cosechada_ha de todos los tipos de Arroz',
       'Arroz: produccion_t de todos los tipos de Arroz',
       'Arroz: area_sembrada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Arroz: area_sembrada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Arroz: area_sembrada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Arroz: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Arroz: area_sembrada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Arroz: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Arroz: area_sembrada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Arroz: area_sembrada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Arroz: area_cosechada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Arroz: area_cosechada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Arroz: area_cosechada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Arroz: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Arroz: area_cosechada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Arroz: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Arroz: area_cosechada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Arroz: area_cosechada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Arroz: produccion_t de los demás cultivos - grupo de cultivos Hortalizas',
       'Arroz: produccion_t de los demás cultivos - grupo de cultivos Leguminosas',
       'Arroz: produccion_t de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Arroz: produccion_t de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Arroz: produccion_t de los demás cultivos - grupo de cultivos Frutales',
       'Arroz: produccion_t de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Arroz: produccion_t de los demás cultivos - grupo de cultivos Cereales',
       'Arroz: produccion_t de los demás cultivos - grupo de cultivos Oleaginosas',
       'Arroz: area_sembrada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Arroz: area_sembrada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Arroz: area_cosechada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Arroz: area_cosechada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Arroz: produccion_t de los demás cultivos - cultivos de ciclo Transitorio',
       'Arroz: produccion_t de los demás cultivos - cultivos de ciclo Permanente',
       'Maíz: area_sembrada_ha de todos los tipos de Maíz',
       'Maíz: area_cosechada_ha de todos los tipos de Maíz',
       'Maíz: produccion_t de todos los tipos de Maíz',
       'Maíz: area_sembrada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Maíz: area_sembrada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Maíz: area_sembrada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Maíz: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Maíz: area_sembrada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Maíz: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Maíz: area_sembrada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Maíz: area_sembrada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Maíz: area_cosechada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Maíz: area_cosechada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Maíz: area_cosechada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Maíz: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Maíz: area_cosechada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Maíz: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Maíz: area_cosechada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Maíz: area_cosechada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Maíz: produccion_t de los demás cultivos - grupo de cultivos Hortalizas',
       'Maíz: produccion_t de los demás cultivos - grupo de cultivos Leguminosas',
       'Maíz: produccion_t de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Maíz: produccion_t de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Maíz: produccion_t de los demás cultivos - grupo de cultivos Frutales',
       'Maíz: produccion_t de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Maíz: produccion_t de los demás cultivos - grupo de cultivos Oleaginosas',
       'Maíz: produccion_t de los demás cultivos - grupo de cultivos Cereales',
       'Maíz: area_sembrada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Maíz: area_sembrada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Maíz: area_cosechada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Maíz: area_cosechada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Maíz: produccion_t de los demás cultivos - cultivos de ciclo Transitorio',
       'Maíz: produccion_t de los demás cultivos - cultivos de ciclo Permanente',
       'Palma de aceite: area_sembrada_ha de todos los tipos de Palma de aceite',
       'Palma de aceite: area_cosechada_ha de todos los tipos de Palma de aceite',
       'Palma de aceite: produccion_t de todos los tipos de Palma de aceite',
       'Palma de aceite: area_sembrada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Palma de aceite: area_sembrada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Palma de aceite: area_sembrada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Palma de aceite: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Palma de aceite: area_sembrada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Palma de aceite: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Palma de aceite: area_sembrada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Palma de aceite: area_sembrada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Palma de aceite: area_cosechada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Palma de aceite: area_cosechada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Palma de aceite: area_cosechada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Palma de aceite: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Palma de aceite: area_cosechada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Palma de aceite: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Palma de aceite: area_cosechada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Palma de aceite: area_cosechada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Palma de aceite: produccion_t de los demás cultivos - grupo de cultivos Hortalizas',
       'Palma de aceite: produccion_t de los demás cultivos - grupo de cultivos Leguminosas',
       'Palma de aceite: produccion_t de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Palma de aceite: produccion_t de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Palma de aceite: produccion_t de los demás cultivos - grupo de cultivos Frutales',
       'Palma de aceite: produccion_t de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Palma de aceite: produccion_t de los demás cultivos - grupo de cultivos Cereales',
       'Palma de aceite: produccion_t de los demás cultivos - grupo de cultivos Oleaginosas',
       'Palma de aceite: area_sembrada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Palma de aceite: area_sembrada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Palma de aceite: area_cosechada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Palma de aceite: area_cosechada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Palma de aceite: produccion_t de los demás cultivos - cultivos de ciclo Transitorio',
       'Palma de aceite: produccion_t de los demás cultivos - cultivos de ciclo Permanente',
       'Caña: area_sembrada_ha de todos los tipos de Caña',
       'Caña: area_cosechada_ha de todos los tipos de Caña',
       'Caña: produccion_t de todos los tipos de Caña',
       'Caña: area_sembrada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Caña: area_sembrada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Caña: area_sembrada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Caña: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Caña: area_sembrada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Caña: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Caña: area_sembrada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Caña: area_sembrada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Caña: area_cosechada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Caña: area_cosechada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Caña: area_cosechada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Caña: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Caña: area_cosechada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Caña: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Caña: area_cosechada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Caña: area_cosechada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Caña: produccion_t de los demás cultivos - grupo de cultivos Hortalizas',
       'Caña: produccion_t de los demás cultivos - grupo de cultivos Leguminosas',
       'Caña: produccion_t de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Caña: produccion_t de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Caña: produccion_t de los demás cultivos - grupo de cultivos Frutales',
       'Caña: produccion_t de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Caña: produccion_t de los demás cultivos - grupo de cultivos Cereales',
       'Caña: produccion_t de los demás cultivos - grupo de cultivos Oleaginosas',
       'Caña: area_sembrada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Caña: area_sembrada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Caña: area_cosechada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Caña: area_cosechada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Caña: produccion_t de los demás cultivos - cultivos de ciclo Transitorio',
       'Caña: produccion_t de los demás cultivos - cultivos de ciclo Permanente',
       'Plátano: area_sembrada_ha de todos los tipos de Plátano',
       'Plátano: area_cosechada_ha de todos los tipos de Plátano',
       'Plátano: produccion_t de todos los tipos de Plátano',
       'Plátano: area_sembrada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Plátano: area_sembrada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Plátano: area_sembrada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Plátano: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Plátano: area_sembrada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Plátano: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Plátano: area_sembrada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Plátano: area_sembrada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Plátano: area_cosechada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Plátano: area_cosechada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Plátano: area_cosechada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Plátano: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Plátano: area_cosechada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Plátano: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Plátano: area_cosechada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Plátano: area_cosechada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Plátano: produccion_t de los demás cultivos - grupo de cultivos Hortalizas',
       'Plátano: produccion_t de los demás cultivos - grupo de cultivos Leguminosas',
       'Plátano: produccion_t de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Plátano: produccion_t de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Plátano: produccion_t de los demás cultivos - grupo de cultivos Frutales',
       'Plátano: produccion_t de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Plátano: produccion_t de los demás cultivos - grupo de cultivos Cereales',
       'Plátano: produccion_t de los demás cultivos - grupo de cultivos Oleaginosas',
       'Plátano: area_sembrada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Plátano: area_sembrada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Plátano: area_cosechada_ha de los demás cultivos - cultivos de ciclo Transitorio',
       'Plátano: area_cosechada_ha de los demás cultivos - cultivos de ciclo Permanente',
       'Plátano: produccion_t de los demás cultivos - cultivos de ciclo Transitorio',
       'Plátano: produccion_t de los demás cultivos - cultivos de ciclo Permanente',
       'Yuca: area_sembrada_ha de todos los tipos de Yuca',
       'Yuca: area_cosechada_ha de todos los tipos de Yuca',
       'Yuca: produccion_t de todos los tipos de Yuca',
       'Yuca: area_sembrada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Yuca: area_sembrada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Yuca: area_sembrada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Yuca: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Yuca: area_sembrada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Yuca: area_sembrada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Yuca: area_sembrada_ha de los demás cultivos - grupo de cultivos Cereales',
       'Yuca: area_sembrada_ha de los demás cultivos - grupo de cultivos Oleaginosas',
       'Yuca: area_cosechada_ha de los demás cultivos - grupo de cultivos Hortalizas',
       'Yuca: area_cosechada_ha de los demás cultivos - grupo de cultivos Leguminosas',
       'Yuca: area_cosechada_ha de los demás cultivos - grupo de cultivos Raíces y tubérculos',
       'Yuca: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos tropicales tradicionales',
       'Yuca: area_cosechada_ha de los demás cultivos - grupo de cultivos Frutales',
       'Yuca: area_cosechada_ha de los demás cultivos - grupo de cultivos Cultivos para condimentos, bebidas medicinales y aromáticas',
       'Yuca: area_cosechada_ha de los demás cultivos - grupo de cultivos Cereales',

-------------------------------- Resumen por cultivo

                              count                                             sum
variable_medicion area_cosechada_ha area_sembrada_ha produccion_t area_cosechada_ha area_sembrada_ha     produccion_t
variable_sujeto
Aguacate                     153123           153123       153123    161,489,226.12   182,946,488.30 2,035,234,699.00
Ahuyama                      148894           148894       148894    162,284,670.50   184,030,644.42 2,042,613,503.12
Algodón                      144817           144817       144817    162,003,566.08   183,759,752.29 2,043,643,257.28
Arroz                        155408           155408       155408    151,914,359.43   173,305,189.15 1,989,069,772.43
Arveja                       153404           153404       153404    161,932,837.30   183,665,787.25 2,043,459,956.11
Banano                       147649           147649       147649    160,937,866.53   182,619,269.84 2,005,868,652.37
Cacao                        152202           152202       152202    159,372,394.21   180,487,611.89 2,042,893,478.33
Café                         153937           153937       153937    149,209,630.23   168,210,709.69 2,030,807,088.93
Caña                         155274           155274       155274    154,746,813.11   175,411,640.94 1,489,921,567.72
Coco                         145072           145072       145072    162,127,534.35   183,847,419.02 2,042,325,059.98
Frijol                       160831           160831       160831    160,385,293.14   181,988,812.35 2,041,893,516.99
Habichuela                   149513           149513       149513    162,336,070.79   184,099,855.44 2,043,599,969.29
Limón                        149314           149314       149314    162,156,950.33   183,869,038.51 2,040,858,993.00
Lulo                         148904           148904       148904    162,307,034.69   184,044,190.18 2,043,206,986.90
Mango                        147651           147651       147651    161,970,137.25   183,657,450.34 2,039,403,032.66
Maíz                         176386           176386       176386    152,523,538.40   173,346,048.54 2,017,982,319.25
Mora                         148782           148782       148782    162,211,050.30   183,951,381.27 2,042,349,526.75
Naranja                      148743           148743       148743    162,023,483.00   183,744,467.70 2,037,923,321.66
Otros cítricos               146978           146978       146978    161,965,752.33   183,662,490.32 2,036,628,752.54
Palma de aceite              144158           144158       144158    154,172,823.95   174,185,811.59 2,016,837,714.34
Papa                         153432           153432       153432    159,307,571.52   180,890,044.65 1,981,287,489.53
Patilla                      147288           147288       147288    162,269,520.39   184,014,121.71 2,041,517,495.71
Piña                         147546           147546       147546    162,141,886.21   183,815,137.34 2,032,040,270.01
Plátano                      156467           156467       156467    155,148,822.46   176,134,658.18 1,977,333,735.65
Soya                         144314           144314       144314    161,529,778.26   183,315,139.13 2,042,267,815.84
Tomate                       157682           157682       157682    162,152,650.78   183,904,010.72 2,031,924,593.85
Tomate de árbol              148087           148087       148087    162,282,174.54   184,018,315.68 2,041,511,039.96
Yuca                         153563           153563       153563    159,012,335.96   180,299,410.66 2,006,326,442.80
Ñame                         146784           146784       146784    161,868,437.47   183,565,840.88 2,037,930,771.80

-------------------------------- Resumen por anno

                              count                                             sum
variable_medicion area_cosechada_ha area_sembrada_ha produccion_t area_cosechada_ha area_sembrada_ha     produccion_t
anno
2006                         105287           105287       105287     43,610,086.22    45,976,649.05   237,875,247.43
2007                         225544           225544       225544    225,104,010.37   253,743,218.96 2,456,478,420.09
2008                         222517           222517       222517    225,235,779.48   256,914,359.59 2,357,019,364.26
2009                         226841           226841       226841    226,356,897.58   260,786,278.57 2,615,225,735.57
2010                         228338           228338       228338    222,183,930.62   266,465,419.72 2,417,132,733.77
2011                         226711           226711       226711    231,861,284.80   275,794,070.18 2,582,202,279.85
2012                         229752           229752       229752    235,785,117.32   280,583,084.01 2,499,717,964.67
2013                         234368           234368       234368    250,101,974.67   289,294,922.40 2,657,458,700.58
2014                         232582           232582       232582    241,178,346.33   280,574,735.40 2,767,711,522.93
2015                         234767           234767       234767    248,571,111.13   287,703,595.60 2,852,152,024.67
2016                         238580           238580       238580    263,576,023.25   306,453,148.71 2,986,457,483.88
2017                         240449           240449       240449    265,735,714.97   304,936,580.25 3,085,905,995.86
2018                         240642           240642       240642    260,072,528.22   292,368,460.34 3,116,995,439.62
2019                         244942           244942       244942    271,492,883.24   300,271,717.51 4,066,361,488.42
2020                         247737           247737       247737    284,884,006.46   311,005,439.18 4,158,525,610.59
2021                         249566           249566       249566    284,520,594.37   309,414,993.42 4,231,999,252.95
2022                         251155           251155       251155    283,116,180.79   305,791,109.03 4,310,328,201.08
2023                         252136           252136       252136    286,123,819.44   312,153,060.69 4,398,862,319.24
2024                         254289           254289       254289    284,273,920.33   314,559,895.35 4,520,251,038.37

In [3]:
run_2001_descargar_poligonostitulosmineros()

Expendientes Totales: 2807
Expendientes de Oro: 268

  0%|                                                                                           | 0/10 [00:00<?, ?it/s]Object converted in non-standard crs - {'wkid': 102100, 'latestWkid': 3857}
Object converted in non-standard crs - {'wkid': 102100, 'latestWkid': 3857}
 20%|████████████████▌                                                                  | 2/10 [00:00<00:00, 11.17it/s]Object converted in non-standard crs - {'wkid': 102100, 'latestWkid': 3857}
Object converted in non-standard crs - {'wkid': 102100, 'latestWkid': 3857}
 40%|█████████████████████████████████▏                                                 | 4/10 [00:00<00:00,  9.61it/s]Object converted in non-standard crs - {'wkid': 102100, 'latestWkid': 3857}
Object converted in non-standard crs - {'wkid': 102100, 'latestWkid': 3857}
 60%|█████████████████████████████████████████████████▊                                 | 6/10 [00:00<00:00, 11.89it/s]Object converted in non-standard crs - {'wkid': 102100, 'latestWkid': 3857}
Object converted in non-standard crs - {'wkid': 102100, 'latestWkid': 3857}
 80%|██████████████████████████████████████████████████████████████████▍                | 8/10 [00:00<00:00, 10.71it/s]Object converted in non-standard crs - {'wkid': 102100, 'latestWkid': 3857}
Object converted in non-standard crs - {'wkid': 102100, 'latestWkid': 3857}
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 11.23it/s]

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   geometry                       10 non-null     geometry
 1   CODIGO_EXPEDIENTE              10 non-null     object
 2   MODALIDAD                      10 non-null     object
 3   TITULO_ESTADO                  10 non-null     object
 4   AREA_HA                        10 non-null     float64
 5   CLASIFICACION_MINERIA          10 non-null     object
 6   ETAPA                          10 non-null     object
 7   SOLICITANTES_O_TITULARES       10 non-null     object
 8   MINERALES                      10 non-null     object
 9   FECHA_DE_SOLICITUD             10 non-null     int64
 10  FECHA_DE_EXPEDICION            10 non-null     int64
 11  FECHA_DE_ANIVERSARIO           10 non-null     int64
 12  FECHA_DE_EXPIRACION            10 non-null     int64
 13  PUBLICADO_EN_RUCOM             10 non-null     object
 14  PAR                            10 non-null     object
 15  TITLE_TYPE_CODE                10 non-null     object
 16  TENURE_STATUS_CODE             10 non-null     object
 17  MINING_CLASSIFICATION_CODE     10 non-null     object
 18  TENURE_STAGE_CODE              10 non-null     object
 19  CENTROID_COORDINATE            10 non-null     object
 20  TENURE_ID                      10 non-null     object
 21  OBJECTID                       10 non-null     int64
 22  MUNICIPIOS                     10 non-null     object
 23  DEPARTAMENTOS                  10 non-null     object
 24  MINERALES_INACTIVOS            1 non-null      object
 25  TIPO_TERMINACION               0 non-null      object
 26  TERMINATION_TYPE_CODE          0 non-null      object
 27  ACTIVE_TENURE_STATUS_IND       10 non-null     object
 28  ACTIVE_APPLICATION_STATUS_IND  10 non-null     object
dtypes: float64(1), geometry(1), int64(5), object(22)
memory usage: 2.4+ KB
None

In [ ]:
run_2011_armonizar_taxonomias()