# Setup

In [20]:
# define root path of project 
from pathlib import Path
import sys

ROOT = Path("..").resolve()
sys.path.append(str(ROOT))

# load general setup
from utils.setup_general import *

# load GIS setup
from utils.setup_gis_python import *

# Load utils for SR 2021
from utils.utils_for_SR2021 import *

# Poligonos de zonas con potencial mineral

## Cargar datos

In [4]:
potencialMineral_g1 = gpd.read_file(DATA/'raw/aba_SGC_zonas_potenciales_minerales/G1_metales_preciosos/75f31543-bd1b-43bc-942f-99932ea7eba92020412-1-1srbe6r.4f47.shp')
potencialMineral_g2 = gpd.read_file(DATA/'raw/aba_SGC_zonas_potenciales_minerales/G2_metales_basicos/Recursos_Minerales_Grupo2__Metales_Básicos.shp')
potencialMineral_g3 = gpd.read_file(DATA/'raw/aba_SGC_zonas_potenciales_minerales/G3_metales_ind_acero/Zonas_Potenciales_Integradas_Recursos_Minerales_Grupo_3_%3A_Metales_de_la_industria_del_acero.shp')
potencialMineral_g4 = gpd.read_file(DATA/'raw/aba_SGC_zonas_potenciales_minerales/G4_metales_especiales/Zonas_Potenciales_Integradas_Recursos_Minerales_Grupo_4_%3A_Metales_Especiales.shp')
potencialMineral_g5 = gpd.read_file(DATA/'raw/aba_SGC_zonas_potenciales_minerales/G5_minerales_industriales/d5ad3fe1-0afc-4b18-b732-d0efb988f4b1202041-1-1eas1dw.4z55.shp')
potencialMineral_g6 = gpd.read_file(DATA/'raw/aba_SGC_zonas_potenciales_minerales/G6_minerales_energeticos/xn--Zonas_Potenciales_Integradas_Recursos_Minerales_Grupo_6__Minerales_Enrgeticos-8zg.shp')
potencialMineral_g7 = gpd.read_file(DATA/'raw/aba_SGC_zonas_potenciales_minerales/G7_materiales_construccion/b13056a7-dc5a-4eb5-9d8e-947fff89f2762020412-1-1qufl83.jrss.shp')

# Agrupar en lista para facilitar la exploración
lista_dfs = [potencialMineral_g1,
                    potencialMineral_g2,
                    potencialMineral_g3,
                    potencialMineral_g4,
                    potencialMineral_g5,
                    potencialMineral_g6,
                    potencialMineral_g7]

## Explorar taxonomía
- En estas bases de datos, las columnas que definien las categorías de las zonas de potencial son ```GR_MINERAL``` y ```SUBGRUPO_M```
- Voy a contar cuantos polígonos hay en cada una de esas categorías

In [5]:
# Explorar las columnas disponibles en cada DF
columnas = pd.DataFrame([df.columns.to_list() for df in lista_dfs])
display(columnas)

# Como los nomobres de las columnas de interes coinciden, puedo concatenar los datos
potencialMineral = pd.concat(lista_dfs)
display(potencialMineral.info())

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
0,FID,OBJECTID,IDZPI,NOMBRE,GR_MINERAL,SUBGRUPO_M,ELEM_PRINC,ANOMALIAS,DESC_TEMAT,DESC_GEOGR,NUM_ANOM,POTENCIAL,T_MINERIA,RESTRICCIO,RAN_GRAV,RAN_MAGN,CAL_ANOM,CAL_FGRA,CAL_FMAG,SUM_POND,CALIFICA,SHAPE_AREA,SHAPE_LEN,Shape__Are,Shape__Len,geometry
1,OBJECTID_1,IDZPI,NOMBRE,GR_MINERAL,SUBGRUPO_M,ELEM_PRINC,ANOMALIAS,DESC_TEMAT,DESC_GEOGR,NUM_ANOM,POTENCIAL,T_MINERIA,RESTRICCIO,RAN_GRAV,RAN_MAGN,SUM_POND,CALIFICA,CAL_ANOM,CAL_FGRA,CAL_FMAG,SHAPE_AREA,SHAPE_LEN,geometry,None,None,None
2,FID,OBJECTID,IDZPI,NOMBRE,GR_MINERAL,SUBGRUPO_M,ELEM_PRINC,ANOMALIAS,DESC_TEMAT,DESC_GEOGR,NUM_ANOM,POTENCIAL,T_MINERIA,RESTRICCIO,RAN_GRAV,RAN_MAGN,CAL_ANOM,CAL_FGRA,CAL_FMAG,SUM_POND,CALIFICA,SHAPE_AREA,SHAPE_LEN,Shape__Are,Shape__Len,geometry
3,FID,OBJECTID,IDZPI,NOMBRE,GR_MINERAL,SUBGRUPO_M,ELEM_PRINC,ANOMALIAS,DESC_TEMAT,DESC_GEOGR,NUM_ANOM,POTENCIAL,T_MINERIA,RESTRICCIO,RAN_GRAV,RAN_MAGN,CAL_ANOM,CAL_FGRA,CAL_FMAG,SUM_POND,CALIFICA,SHAPE_AREA,SHAPE_LEN,Shape__Are,Shape__Len,geometry
4,FID,OBJECTID,IDZPI,NOMBRE,GR_MINERAL,SUBGRUPO_M,ELEM_PRINC,ANOMALIAS,DESC_TEMAT,DESC_GEOGR,NUM_ANOM,POTENCIAL,T_MINERIA,RESTRICCIO,RAN_GRAV,RAN_MAGN,CAL_ANOM,CAL_FGRA,CAL_FMAG,SUM_POND,CALIFICA,SHAPE_AREA,SHAPE_LEN,Shape__Are,Shape__Len,geometry
5,FID,OBJECTID,IDZPI,NOMBRE,GR_MINERAL,SUBGRUPO_M,ELEM_PRINC,ANOMALIAS,DESC_TEMAT,DESC_GEOGR,NUM_ANOM,POTENCIAL,T_MINERIA,RESTRICCIO,RAN_GRAV,RAN_MAGN,CAL_ANOM,CAL_FGRA,CAL_FMAG,SUM_POND,CALIFICA,SHAPE_AREA,SHAPE_LEN,Shape__Are,Shape__Len,geometry
6,FID,OBJECTID,IDZPI,NOMBRE,GR_MINERAL,SUBGRUPO_M,ANOMALIAS,DESC_TEMAT,DESC_GEOGR,NUM_ANOM,T_MINERIA,RESTRICCIO,RAN_GRAV,RAN_MAGN,ELEM_PRINC,CAL_ANOM,CAL_FGRA,CAL_FMAG,SUM_POND,CALIFICA,POTENCIAL,SHAPE_AREA,SHAPE_LEN,Shape__Are,Shape__Len,geometry

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 728 entries, 0 to 163
Data columns (total 27 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FID         608 non-null    float64
 1   OBJECTID    608 non-null    float64
 2   IDZPI       728 non-null    object
 3   NOMBRE      728 non-null    object
 4   GR_MINERAL  728 non-null    object
 5   SUBGRUPO_M  559 non-null    object
 6   ELEM_PRINC  728 non-null    object
 7   ANOMALIAS   544 non-null    object
 8   DESC_TEMAT  544 non-null    object
 9   DESC_GEOGR  544 non-null    object
 10  NUM_ANOM    728 non-null    object
 11  POTENCIAL   728 non-null    object
 12  T_MINERIA   491 non-null    object
 13  RESTRICCIO  461 non-null    object
 14  RAN_GRAV    728 non-null    object
 15  RAN_MAGN    443 non-null    object
 16  CAL_ANOM    728 non-null    float64
 17  CAL_FGRA    728 non-null    float64
 18  CAL_FMAG    728 non-null    float64
 19  SUM_POND    728 non-null    float64
 20  CALIFICA    728 non-null    float64
 21  SHAPE_AREA  728 non-null    float64
 22  SHAPE_LEN   728 non-null    float64
 23  Shape__Are  608 non-null    float64
 24  Shape__Len  608 non-null    float64
 25  geometry    728 non-null    geometry
 26  OBJECTID_1  120 non-null    float64
dtypes: float64(12), geometry(1), object(14)
memory usage: 159.2+ KB

None

In [7]:
# Contar el numero de registros de cada categoria de mierales
categorias_potencialMineral = potencialMineral.groupby(['SUBGRUPO_M', 'ELEM_PRINC'])['geometry'].count().to_frame().reset_index().sort_values(by='geometry', ascending=False)
display(categorias_potencialMineral.head(3))

              SUBGRUPO_M             ELEM_PRINC  geometry
192    MINERALES DEL ORO                     Au        40
1      AGREGADOS PETREOS  ARCILLAS INDUSTRIALES        26
173  MINERALES DE URANIO                      U        24

# Poligonos de distritos aluviales

In [8]:
# Cargar datos
distritosAluviales = gpd.read_file(DATA/'raw/abb_SGC_distritos_aluviales/Mapa_Metalog%C3%A9nico_de_Colombia_2020%3A_Distrito_Aluvial.shp')

# Mostrar informacion basica
display(distritosAluviales.info())

# Explorar DF
display(distritosAluviales)

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FID         31 non-null     int32
 1   OBJECTID    31 non-null     int32
 2   No_Distrit  31 non-null     int32
 3   DMM_NOMB_D  31 non-null     object
 4   METAL       31 non-null     object
 5   Shape_Leng  31 non-null     float64
 6   CODE_2020   31 non-null     object
 7   Shape__Len  31 non-null     float64
 8   geometry    31 non-null     geometry
dtypes: float64(2), geometry(1), int32(3), object(3)
memory usage: 1.9+ KB

None

,FID,OBJECTID,No_Distrit,DMM_NOMB_D,METAL,Shape_Leng,CODE_2020,Shape__Len,geometry
0,1,1,14,ALUVIÓN AURÍFERO RÍO NECHÍ,Au,0.95,0124,"106,615.65","LINESTRING (-8323291.301 904259.877, -8323052...."
1,2,2,8,ALUVIÓN AURÍFERO RÍO CAUCA,Au,14.23,0124,"1,591,541.87","MULTILINESTRING ((-8417057.437 640766.422, -84..."
2,3,3,2,ALUVIÓN AURÍFERO-PLATINÍFERO RÍO ATRATO,Au-Pt,15.94,0138,"1,779,320.67","MULTILINESTRING ((-8540323.137 582919.966, -85..."
3,4,4,7,ALUVIÓN AURÍFERO RÍO CALIMA,Au,2.27,0124,"252,882.53","MULTILINESTRING ((-8548481.321 432880.656, -85..."
4,5,5,10,ALUVIÓN AURÍFERO RÍO DAGUA,Au,1.46,0124,"162,832.60","MULTILINESTRING ((-8548291.513 424511.321, -85..."
5,6,6,5,ALUVIÓN AURÍFERO RÍO ANCHICAYÁ,Au,1.21,0124,"134,727.84","MULTILINESTRING ((-8586217.613 423175.977, -85..."
6,7,7,16,ALUVIÓN AURÍFERO RÍO RAPOSO,Au,1.39,0124,"155,146.36","MULTILINESTRING ((-8584812.433 411954.54, -858..."
7,8,8,1,ALUVIÓN AURÍFERO-PLATINÍFERO RIÍO SAN JUAN,Au-Pt,13.81,0138,"1,539,944.67","MULTILINESTRING ((-8576865.816 468831.342, -85..."
8,9,9,23,ALUVIÓN TITANÍFERO SNSM,Ti,0.77,0180,"86,170.20","MULTILINESTRING ((-8207949.843 1248115.195, -8..."
9,10,10,17,ALUVIÓN AURÍFERO RÍO SALDAÑA,Au,1.80,0124,"200,100.26","MULTILINESTRING ((-8371395.961 421968.836, -83..."
10,11,11,4,ALUVIÓN AURÍFERO CAÑOS BOCÓN / CUICA,Au,6.30,0124,"701,685.93","MULTILINESTRING ((-7724498.062 356649.613, -77..."
11,12,12,9,ALUVIÓN AURÍFERO RÍO CUDUYARÍ,Au,1.48,0124,"164,771.33","MULTILINESTRING ((-7908783.381 161964.451, -79..."
12,13,13,12,ALUVIÓN AURÍFERO RÍO INÍRIDA,Au,22.25,0124,"2,478,396.81","MULTILINESTRING ((-7563902.996 430088.3, -7563..."
13,14,15,6,ALUVIÓN AURÍFERO RÍO AQUIO,Au,1.83,0124,"203,463.32","LINESTRING (-7572429.993 202281.964, -7572661...."
14,15,16,11,ALUVIÓN AURÍFERO RÍO GUANÍA,Au,9.06,0124,"1,009,357.27","MULTILINESTRING ((-7471127.403 223131.996, -74..."
15,16,17,21,ALUVIÓN AURÍFERO RÍO VAUPÉS,Au,17.44,0124,"1,941,673.21","MULTILINESTRING ((-8028134.57 153930.465, -802..."
16,17,18,20,ALUVIÓN AURÍFERO RÍO TOMO / GUAINÍA,Au,1.20,0124,"133,415.85","MULTILINESTRING ((-7539148.055 224191.759, -75..."
17,18,19,18,ALUVIÓN AURÍFERO RÍO TARAIRA,Au,3.25,0124,"361,450.92","MULTILINESTRING ((-7797638.024 -12199.696, -77..."
18,19,20,13,ALUVIÓN AURÍFERO RÍO MICAY,Au,2.16,0124,"240,304.92","MULTILINESTRING ((-8628694.024 353634.673, -86..."
19,20,21,19,ALUVIÓN AURÍFERO RÍO TIMBIQUÍ,Au,2.00,0124,"223,122.67","MULTILINESTRING ((-8646817.071 309829.407, -86..."
20,21,22,22,ALUVIÓN AURÍFERO RÍOS GUAPI / NAPI,Au,6.18,0124,"687,722.88","MULTILINESTRING ((-8668838.988 289692.832, -86..."
21,22,23,15,ALUVIÓN AURÍFERO RÍO PATÍA,Au,15.03,0124,"1,672,673.09","MULTILINESTRING ((-8737343.372 253677.254, -87..."
22,23,24,25,ALUVIÓN AURÍFERO CAÑO MAIMACHI RÍO NAQUEN,Au,0.52,0124,"57,556.42","LINESTRING (-7594760.8 219792.814, -7594943.56..."
23,24,25,26,ALUVIÓN AURÍFERO RÍO CUIARÍ,Au,3.56,0124,"396,124.11","MULTILINESTRING ((-7587902.971 192365.675, -75..."
24,25,26,27,ALUVIÓN AURÍFERO RÍOS PORCE/ MEDELLÍN,Au,3.66,0124,"409,193.67","MULTILINESTRING ((-8372263.263 731116.442, -83..."
25,26,27,0,ALUVIÓN AURÍFERO-PLATINÍFERO RÍO SIPÍ,Au-Pt,0.51,0138,"57,214.84","LINESTRING (-8494698.444 520153.344, -8494935...."
26,27,28,28,ALUVIÓN AURÍFERO RÍO CAQUETÁ,Au,11.48,0124,"1,277,550.16","MULTILINESTRING ((-8310927.189 -1785.769, -831..."
27,28,30,29,ALUVIÓN AURÍFERO RÍO PUTUMAYO,Au,9.64,0124,"1,073,361.61","MULTILINESTRING ((-8332551.078 -26628.452, -83..."
28,29,32,30,ALUVIÓN AURÍFERO RÍO LEÓN,Au,0.70,0124,"78,553.64","LINESTRING (-8532300.88 832256.273, -8531974.1..."
29,30,33,3,ALUVIÓN AURÍFERO CAÑO CHAQUITA,Au,0.53,0124,"58,502.16","LINESTRING (-7547277.805 365234.554, -7547354...."
30,31,34,3,ALUVIÓN AURÍFERO CAÑO CHAQUITA,Au,0.33,0124,"36,939.50","LINESTRING (-7526369.779 397778.845, -7526361...."

In [9]:
# En este DF, la columna relevante es "METAL"
categorias_distritosAluviales = distritosAluviales.groupby(['METAL'])['geometry'].count().reset_index().sort_values(by='geometry', ascending=False)
display(categorias_distritosAluviales)

   METAL  geometry
0     Au        27
1  Au-Pt         3
2     Ti         1

# Titulos mineros

In [10]:
# cargar datos
titulosMineros = pd.read_parquet(DATA/'raw/aad_ANM_titulos_mineros_poligonos/2001_poligonos_titulosmineros.parquet')

# explorar datos
display(titulosMineros.info())
display(titulosMineros.head())

<class 'pandas.core.frame.DataFrame'>
Index: 2772 entries, 0 to 236
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   geometry                       2772 non-null   object
 1   CODIGO_EXPEDIENTE              2772 non-null   object
 2   MODALIDAD                      2772 non-null   object
 3   TITULO_ESTADO                  2772 non-null   object
 4   AREA_HA                        2772 non-null   float64
 5   CLASIFICACION_MINERIA          2744 non-null   object
 6   ETAPA                          2772 non-null   object
 7   SOLICITANTES_O_TITULARES       2772 non-null   object
 8   MINERALES                      2772 non-null   object
 9   FECHA_DE_SOLICITUD             2772 non-null   int64
 10  FECHA_DE_EXPEDICION            2772 non-null   int64
 11  FECHA_DE_ANIVERSARIO           2772 non-null   int64
 12  FECHA_DE_EXPIRACION            2710 non-null   float64
 13  PUBLICADO_EN_RUCOM             2772 non-null   object
 14  PAR                            2772 non-null   object
 15  TITLE_TYPE_CODE                2772 non-null   object
 16  TENURE_STATUS_CODE             2772 non-null   object
 17  MINING_CLASSIFICATION_CODE     2744 non-null   object
 18  TENURE_STAGE_CODE              2772 non-null   object
 19  CENTROID_COORDINATE            2772 non-null   object
 20  TENURE_ID                      2772 non-null   object
 21  OBJECTID                       2772 non-null   int64
 22  MUNICIPIOS                     2772 non-null   object
 23  DEPARTAMENTOS                  2772 non-null   object
 24  MINERALES_INACTIVOS            160 non-null    object
 25  TIPO_TERMINACION               4 non-null      object
 26  TERMINATION_TYPE_CODE          4 non-null      object
 27  ACTIVE_TENURE_STATUS_IND       2772 non-null   object
 28  ACTIVE_APPLICATION_STATUS_IND  2772 non-null   object
dtypes: float64(2), int64(4), object(23)
memory usage: 649.7+ KB

None

,geometry,CODIGO_EXPEDIENTE,MODALIDAD,TITULO_ESTADO,AREA_HA,CLASIFICACION_MINERIA,ETAPA,SOLICITANTES_O_TITULARES,MINERALES,FECHA_DE_SOLICITUD,FECHA_DE_EXPEDICION,FECHA_DE_ANIVERSARIO,FECHA_DE_EXPIRACION,PUBLICADO_EN_RUCOM,PAR,TITLE_TYPE_CODE,TENURE_STATUS_CODE,MINING_CLASSIFICATION_CODE,TENURE_STAGE_CODE,CENTROID_COORDINATE,TENURE_ID,OBJECTID,MUNICIPIOS,DEPARTAMENTOS,MINERALES_INACTIVOS,TIPO_TERMINACION,TERMINATION_TYPE_CODE,ACTIVE_TENURE_STATUS_IND,ACTIVE_APPLICATION_STATUS_IND
0,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00...,ABQ-101,CONTRATO DE CONCESIÓN (D 2655),Activo,39.08,Mediana,Explotación,(61017) CANTERA LA EMILIA SAS,"DIABASA, RECEBO",920023200000,1015286400000,1015286400000,"2,002,060,800,000.00",Y,PAR CALI,CCD2,A,MED,EXPT,"-76.51667,3.56964",ABQ-101,176246,YUMBO,Valle del Cauca,None,None,None,Y,N
1,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00\x06\x00...",AB1-08C,CONTRATO EN VIRTUD DE APORTE,Activo,35.72,Pequeña,Explotación,(29140) LAUREANO GOMEZ,"ANTRACITA, CARBÓN METALÚRGICO, CARBÓN TÉRMICO",917856000000,1011845199000,1011845199000,"1,327,276,800,000.00",N,PAR NOBSA,CVA,A,PEQ,EXPT,"-72.81173,5.77217",AB1-08C,173771,TÓPAGA,Boyacá,None,None,None,Y,N
2,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x1b\x00...,ACB-112,CONTRATO DE CONCESIÓN (L 685),Activo,87.63,Pequeña,Explotación,(46434) INGENIERIA Y MINERIA DE SANTANDER,GRAVAS,1046736000000,1046790311000,1600164311000,"2,546,726,400,000.00",Y,PAR BUCARAMANGA,CC,A,PEQ,EXPT,"-73.01382,7.28451",ACB-112,173285,"CHARTA, MATANZA",Santander,None,None,None,Y,N
3,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x1a\x00...,ADC-101,CONTRATO DE CONCESIÓN (L 685),Activo,57.30,Mediana,Explotación,(14876) FLOR GRES S.A.S.,"ARCILLA COMUN (ARCILLA CERAMICA), ARENAS, GRAV...",923911200000,1068508800000,1068508800000,"1,915,056,000,000.00",Y,ZONA CENTRO,CC,A,MED,EXPT,"-74.19849,4.54459",ADC-101,174161,SOACHA,Cundinamarca,None,None,None,Y,N
4,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x0b\x00...,ADR-101,CONTRATO EN VIRTUD DE APORTE,Activo,76.40,Pequeña,Construcción y montaje,(12134) MONTGOMERY COAL S.A.S.,"ANTRACITA, CARBÓN METALÚRGICO, CARBÓN TÉRMICO",925207200000,1012531789000,1012531789000,"1,643,587,200,000.00",N,ZONA NORTE,CVA,A,PEQ,CONS,"-72.59096,7.77297",ADR-101,173150,SAN CAYETANO,Norte de Santander,None,None,None,Y,N

In [11]:
# En esta base datos la columna relevante para la clasificacion es "MINERALES"
# Cuento la cantidad de registros por los valores de esa columna
categorias_titulosMineros = titulosMineros.groupby('MINERALES')['geometry'].count().reset_index().sort_values(by='geometry', ascending=False)
display(categorias_titulosMineros)

                                             MINERALES  geometry
107                                     ARENAS, GRAVAS       344
10       ANTRACITA, CARBÓN METALÚRGICO, CARBÓN TÉRMICO       326
71                    ARENAS (DE RIO), GRAVAS (DE RIO)       181
211                               ROCA O PIEDRA CALIZA       154
189                                     MINERAL DE ORO       129
..                                                 ...       ...
1                                            ANTRACITA         1
111   ARENAS, GRAVAS, MINERAL DE ORO, MINERAL DE PLATA         1
112  ARENAS, GRAVAS, MINERAL DE ORO, MINERAL DE PLA...         1
113  ARENAS, GRAVAS, MINERAL DE ORO, MINERAL DE PLA...         1
0    ANHIDRITA, ARCILLA COMUN (ARCILLA CERAMICA), A...         1

[220 rows x 2 columns]

# Produccion asociada a regalias

In [12]:
# cargar datos 
produccionRegalias = pd.read_excel(DATA/'raw/abc_UPME_produccionRegalias/PyRMC.xlsm',
                                   skiprows=1)

# explorar datos
display(produccionRegalias.info())
display(produccionRegalias.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69808 entries, 0 to 69807
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Año                  69808 non-null  int64
 1   Mes                  69808 non-null  int64
 2   Mineral              69808 non-null  object
 3   UnidadMedida         69808 non-null  object
 4   Regalias ($)         69808 non-null  float64
 5   Produccion           69808 non-null  float64
 6   Codigo Municipio     69808 non-null  int64
 7   Municipio            69808 non-null  object
 8   Codigo Departamento  69808 non-null  int64
 9   Departamento         69808 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 5.3+ MB

None

    Año  Mes Mineral UnidadMedida     Regalias ($)  Produccion  Codigo Municipio Municipio  Codigo Departamento Departamento
0  2026    1     ORO       GRAMOS 1,013,843,150.81  634,108.02              5736   SEGOVIA                    5    ANTIOQUIA
1  2025   12     ORO       GRAMOS   969,828,842.90  690,459.19              5736   SEGOVIA                    5    ANTIOQUIA
2  2025   11     ORO       GRAMOS   746,090,262.90  612,155.49              5736   SEGOVIA                    5    ANTIOQUIA

In [13]:
# La columna relevante es mineral
# Contar los registros por las valores de esa columna
categorias_produccionRegalias = produccionRegalias.groupby('Mineral')['Produccion'].count().reset_index().sort_values(by='Produccion', ascending=False)
display(categorias_produccionRegalias)

                                  Mineral  Produccion
53                                    ORO       13128
55                                  PLATA        9954
40                                 GRAVAS        7591
9                                  ARENAS        6287
59                                 RECEBO        4834
..                                    ...         ...
69                               TANTALIO           6
70                                TITANIO           4
43                              MAGNESITA           2
12                                ASBESTO           1
38  GRANITO (BLOQUE MAYOR O IGUAL A 1 M3)           1

[76 rows x 2 columns]

# Mineria Ilegal

In [17]:
# cargar datos 
SR2021Minerales = pd.read_stata(DATA/"raw/ada_SR2021/panel_prillegalMi.dta")

# explorar datos
display(SR2021Minerales.info())
display(SR2021Minerales.head(3))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132132 entries, 0 to 132131
Data columns (total 24 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   codmpio                    132132 non-null  int32
 1   ano                        132132 non-null  float32
 2   mineral                    132132 non-null  int8
 3   propmined_illegal_mi       25946 non-null   float32
 4   w_analizedpctgarea_mi      41950 non-null   float32
 5   analizedareasqkm_mi        131549 non-null  float32
 6   areaminedsqkm_mi           131549 non-null  float32
 7   propadjminedMi_illegal     8817 non-null    float32
 8   areaminedSPsqkm_mi         131571 non-null  float64
 9   areaillegalminedSPsqkm_mi  131571 non-null  float64
 10  propminedSP_illegal_mi     25655 non-null   float32
 11  propminedMi_illegal_prob   15161 non-null   float32
 12  newpropminedMi_illegal     11413 non-null   float32
 13  c12_propmined_illegal_mi   40738 non-null   float32
 14  titulosareaMi_ha           35922 non-null   float32
 15  frtitulosareaMi            35922 non-null   float32
 16  afterxgold                 132132 non-null  float32
 17  ind_after                  132132 non-null  float32
 18  afterxplatinum             132132 non-null  float32
 19  precio                     36036 non-null   float32
 20  regalia_mine               132132 non-null  float32
 21  afterxregalia              132132 non-null  float32
 22  areamuni_sqkm              131890 non-null  float32
 23  propmuni_illegal_mi        25946 non-null   float32
dtypes: float32(20), float64(2), int32(1), int8(1)
memory usage: 12.7 MB

None

,codmpio,ano,mineral,propmined_illegal_mi,w_analizedpctgarea_mi,analizedareasqkm_mi,areaminedsqkm_mi,propadjminedMi_illegal,areaminedSPsqkm_mi,areaillegalminedSPsqkm_mi,propminedSP_illegal_mi,propminedMi_illegal_prob,newpropminedMi_illegal,c12_propmined_illegal_mi,titulosareaMi_ha,frtitulosareaMi,afterxgold,ind_after,afterxplatinum,precio,regalia_mine,afterxregalia,areamuni_sqkm,propmuni_illegal_mi
0,5001,"2,004.00",6,NaN,NaN,0.00,0.00,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,NaN,5.00,0.00,371.53,NaN
1,5001,"2,010.00",2,100.00,80.00,2.39,0.00,NaN,0.00,0.00,100.00,100.00,NaN,100.00,0.00,0.00,0.00,0.00,0.00,1.35,5.00,0.00,371.53,0.00
2,5001,"2,012.00",8,NaN,NaN,0.00,0.00,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1.00,0.00,NaN,12.00,12.00,371.53,NaN

In [19]:
# La columna relevante para la clasificación es "mineral"
# Contar los registros por las valores de esa columna
display(
    SR2021Minerales.groupby('mineral')['codmpio'].count().reset_index().sort_values(by='codmpio', ascending=False))

    mineral  codmpio
0         1    12012
1         2    12012
2         3    12012
3         4    12012
4         5    12012
5         6    12012
6         7    12012
7         8    12012
8         9    12012
9        10    12012
10       11    12012

In [22]:
# Como la base de datos esta codificada, fue necesario encontrar la correspondencia con los minerales
# El diccionario SR2021_mineral_code de /config/utils_for_SR2021.py contiene la correspondencia y la referencia
# que permitió definirlo
display(SR2021_mineral_code)

{1: 'gold',
 2: 'platinum',
 3: 'copper',
 4: 'coal',
 5: 'columbite',
 6: 'iron',
 7: 'magnesium',
 8: 'nickel',
 9: 'phosphate',
 10: 'potassium',
 11: 'uranium'}

In [24]:
# Crear columna con el nombre del mineral decodificado
SR2021Minerales['mineral_decodificado'] = SR2021Minerales['mineral'].map(SR2021_mineral_code)

In [26]:
# Encontrar los categorias de la base de datos
categorias_SR2021Minerales = SR2021Minerales.groupby(['mineral','mineral_decodificado'])['codmpio'].count().reset_index().sort_values(by='codmpio', ascending=False)
display(categorias_SR2021Minerales)

    mineral mineral_decodificado  codmpio
0         1                 gold    12012
1         2             platinum    12012
2         3               copper    12012
3         4                 coal    12012
4         5            columbite    12012
5         6                 iron    12012
6         7            magnesium    12012
7         8               nickel    12012
8         9            phosphate    12012
9        10            potassium    12012
10       11              uranium    12012

# Exportar categorías para armonizar
Exporto a Excel las taxonomías de minerales que se usan en las bases de datos para definir las categorías armonizadas.

Las bases de datos relevantes son 
1. Polígonos de zonas con potencial mineral ```categorias_potencialMineral```
2. Polígonos de distritos aluviales ```categorias_distritosAluviales```
3. Polígonos de títulos mineros ```categorias_titulosMineros```
4. Producción asociada a regalías ```categorias_produccionRegalias```
5. Saavedra & Romero 2021 (minería ilegal) ```categorias_SR2021Minerales```