**Procesar precios de mienrales**

En este cuaderno estructuro la información de los siguientes datos para manejarlos en STATA:
- Precios de minerales armonizados (Fuente: World Bank - PinkSheet)

# Setup

In [1]:
# define root path of project 
from pathlib import Path
import sys

ROOT = Path("..").resolve()
sys.path.append(str(ROOT))

# load general setup
from utils.setup_general import *

Setup general cargado

# Definir datos de salida
El archivo de salida se estructura para conservar la misma estructura entre todas las bases de datos

In [2]:
ORDEN_DF

['codigo_dane_municipio',
 'anno',
 'nombre_variable',
 'variable_sujeto',
 'variable_medicion',
 'variable_detalle',
 'variable_descripcion',
 'valor',
 'clasificacion_econometria']

In [3]:
# Definir DF con la estructura acordada para el proyecto
# La variable global ORDEN_DF ya tiene la lista de todas las columnas ordenadas
# Inicializar el DF vacío
df_salida = pd.DataFrame(
    columns=[ORDEN_DF]
)

# Precios minerales
Fuente: World Bank - Pink Sheet

In [6]:
# Cargar datos
precios_minerales_armonizados = pd.read_parquet(
    DATA/"intermediate/e2011_WbPinkSheet_preciosMinerales_armonizado.parquet"
)

print(MSC_SEPARADOR, "Head")
display(precios_minerales_armonizados.head())

-------------------------------- Head

   periodo                 variable  value      texto_busqueda categoria_armonizada
0  1970M01  Coal, Australian ($/mt)   7.80  coal australian mt               Carbon
1  1970M02  Coal, Australian ($/mt)   7.80  coal australian mt               Carbon
2  1970M03  Coal, Australian ($/mt)   7.80  coal australian mt               Carbon
3  1970M04  Coal, Australian ($/mt)   7.80  coal australian mt               Carbon
4  1970M05  Coal, Australian ($/mt)   7.80  coal australian mt               Carbon

## Procesar las fechas

In [15]:
# Traducir de string a fecha
precios_minerales_armonizados["fecha_mes"] = pd.to_datetime(
    precios_minerales_armonizados["periodo"],
    format="%YM%m"
)

# Crear columna de año para agregar
precios_minerales_armonizados[COL_ANNO] = precios_minerales_armonizados['fecha_mes'].dt.year

## Agregar valores anuales
Pensando en probar hipotesis de que precios altos o bajos pueden generar auges/declives locales, para cada año me interesa tanto el promedio como los valores extremos

In [16]:
# Agregar los valores anualmente
precios_minerales_anuales = (
    precios_minerales_armonizados.groupby(['variable', COL_ANNO], as_index=False)
    .agg(
        precio_promedio=("value", "mean"),
        precio_minimo=("value", "min"),
        precio_maximo=("value", "max"),
        meses_disponibles=("value", "count"),
        categoria_armonizada=("categoria_armonizada", 'first')
    )
)

# Mostrar los nuevos datos
print(MSC_SEPARADOR, "DF")
display(precios_minerales_anuales)

-------------------------------- DF

            variable  anno  precio_promedio  precio_minimo  precio_maximo  meses_disponibles categoria_armonizada
0    Aluminum ($/mt)  1960           511.00         511.00         511.00                 12         Metales base
1    Aluminum ($/mt)  1961           511.00         511.00         511.00                 12         Metales base
2    Aluminum ($/mt)  1962           498.00         496.00         511.00                 12         Metales base
3    Aluminum ($/mt)  1963           498.75         496.00         507.00                 12         Metales base
4    Aluminum ($/mt)  1964           525.92         507.00         540.00                 12         Metales base
..               ...   ...              ...            ...            ...                ...                  ...
966      Zinc ($/mt)  2022         3,481.25       2,939.00       4,360.00                 12         Metales base
967      Zinc ($/mt)  2023         2,652.75       2,375.00       3,310.00                 12         Metales base
968      Zinc ($/mt)  2024         2,775.75       2,360.00       3,106.00                 12         Metales base
969      Zinc ($/mt)  2025         2,867.58       2,622.00       3,177.00                 12         Metales base
970      Zinc ($/mt)  2026         3,386.14       3,182.00       3,599.00                  7         Metales base

[971 rows x 7 columns]

## Estructurar datos de salida

In [58]:
# Estructurar los datos en el formato acordado
precios_minerales_salida = precios_minerales_anuales.melt(
    id_vars=[COL_ANNO, 'variable', 'categoria_armonizada'],
    value_name=COL_VALOR,
    var_name=COL_VARIABLE_MEDICION
)

# Asiganr nombres de variables acordados
precios_minerales_salida = precios_minerales_salida.rename(
    columns={
        'categoria_armonizada':COL_VARIABLE_SUJETO,
        'variable': COL_VARIABLE_DETALLE,
    }
)

# Completar información de columnas
precios_minerales_salida[COL_VARIABLE_DESCRIPCION]= (
    'Precio minerales. ' +
    precios_minerales_salida[COL_VARIABLE_SUJETO] + '. ' +
    precios_minerales_salida[COL_VARIABLE_DETALLE] + '. ' +
    precios_minerales_salida[COL_VARIABLE_MEDICION] + '. '
)
precios_minerales_salida[COL_CLASIFICACION_ECONOMETRIA] ='Instrumento: Precio'
precios_minerales_salida[COL_ID_MUNICIPIO] = None
precios_minerales_salida[COL_NOMBRE_DE_VARIABLE] = ''

In [63]:
print(MSC_SEPARADOR, "Explorar nombres y unidades de medicion")
display(precios_minerales_salida[COL_VARIABLE_DETALLE].unique())

diccionario_abreviaciones_metales_minerales = {
    'Aluminum ($/mt)': 'Al',
    'Coal, Australian ($/mt)': 'C_AU',
    'Coal, South African ** ($/mt)': 'C_SA',
    'Copper ($/mt)': 'Cu',
    'Gold ($/troy oz)': 'oro',
    'Iron ore, cfr spot ($/dmtu)': 'Fe',
    'Lead ($/mt)': 'Pb',
    'Nickel ($/mt)': 'Ni',
    'Phosphate rock ($/mt)': 'phsp',
    'Platinum ($/troy oz)': 'plat',
    'Potassium chloride ** ($/mt)': 'KCl',
    'Silver ($/troy oz)': 'Ag',
    'Tin ($/mt)': 'Sn',
    'Urea  ($/mt)': 'urea',
    'Zinc ($/mt)': 'zinc'
}

diccionario_unidades = {
    'Aluminum ($/mt)': 'USmt',
    'Coal, Australian ($/mt)': 'USmt',
    'Coal, South African ** ($/mt)': 'USmt',
    'Copper ($/mt)': 'USmt',
    'Gold ($/troy oz)': 'USoz',
    'Iron ore, cfr spot ($/dmtu)': 'USmt',
    'Lead ($/mt)': 'USmt',
    'Nickel ($/mt)': 'USmt',
    'Phosphate rock ($/mt)': 'USmt',
    'Platinum ($/troy oz)': 'USoz',
    'Potassium chloride ** ($/mt)': 'USmt',
    'Silver ($/troy oz)': 'USoz',
    'Tin ($/mt)': 'USmt',
    'Urea  ($/mt)': 'USmt',
    'Zinc ($/mt)': 'USmt'
}

print(MSC_SEPARADOR, "Explorar mediciones disponibles")
display(precios_minerales_salida[COL_VARIABLE_MEDICION].unique())

-------------------------------- Explorar nombres y unidades de medicion

array(['Aluminum ($/mt)', 'Coal, Australian ($/mt)',
       'Coal, South African ** ($/mt)', 'Copper ($/mt)',
       'Gold ($/troy oz)', 'Iron ore, cfr spot ($/dmtu)', 'Lead ($/mt)',
       'Nickel ($/mt)', 'Phosphate rock ($/mt)', 'Platinum ($/troy oz)',
       'Potassium chloride ** ($/mt)', 'Silver ($/troy oz)', 'Tin ($/mt)',
       'Urea  ($/mt)', 'Zinc ($/mt)'], dtype=object)

-------------------------------- Explorar mediciones disponibles

array(['precio_promedio', 'precio_minimo', 'precio_maximo',
       'meses_disponibles'], dtype=object)

In [73]:
# Asignar nombres de las variables con la secuencia definida
precios_minerales_salida[COL_NOMBRE_DE_VARIABLE]=(
    'precMine_' + 
    precios_minerales_salida[COL_VARIABLE_SUJETO].map(DICCIONARIO_ABREVIACIONES_MINERALES) + '_' +
    precios_minerales_salida['variable_medicion'].map({
        'precio_promedio':'prmdio', 'precio_minimo':'minimo', 'precio_maximo':'maximo', 'meses_disponibles':'conteo'}) + '_' +
    precios_minerales_salida[COL_VARIABLE_DETALLE].map(diccionario_abreviaciones_metales_minerales) + '_' +
    precios_minerales_salida[COL_VARIABLE_DETALLE].map(diccionario_unidades)
)

print(MSC_SEPARADOR, "Verificar que los nombres de las variables no superen los 32 caracteres")
display(precios_minerales_salida[COL_NOMBRE_DE_VARIABLE].str.len().max())

-------------------------------- Verificar que los nombres de las variables no superen los 32 caracteres

32

In [75]:
print(MSC_SEPARADOR, 'DF de salida')
display(precios_minerales_salida[ORDEN_DF])

-------------------------------- DF de salida

,codigo_dane_municipio,anno,nombre_variable,variable_sujeto,variable_medicion,variable_detalle,variable_descripcion,valor,clasificacion_econometria
0,None,1960,precMine_metBas_prmdio_Al_USmt,Metales base,precio_promedio,Aluminum ($/mt),Precio minerales. Metales base. Aluminum ($/mt...,511.00,Instrumento: Precio
1,None,1961,precMine_metBas_prmdio_Al_USmt,Metales base,precio_promedio,Aluminum ($/mt),Precio minerales. Metales base. Aluminum ($/mt...,511.00,Instrumento: Precio
2,None,1962,precMine_metBas_prmdio_Al_USmt,Metales base,precio_promedio,Aluminum ($/mt),Precio minerales. Metales base. Aluminum ($/mt...,498.00,Instrumento: Precio
3,None,1963,precMine_metBas_prmdio_Al_USmt,Metales base,precio_promedio,Aluminum ($/mt),Precio minerales. Metales base. Aluminum ($/mt...,498.75,Instrumento: Precio
4,None,1964,precMine_metBas_prmdio_Al_USmt,Metales base,precio_promedio,Aluminum ($/mt),Precio minerales. Metales base. Aluminum ($/mt...,525.92,Instrumento: Precio
...,...,...,...,...,...,...,...,...,...
3879,None,2022,precMine_metBas_conteo_zinc_USmt,Metales base,meses_disponibles,Zinc ($/mt),Precio minerales. Metales base. Zinc ($/mt). m...,12.00,Instrumento: Precio
3880,None,2023,precMine_metBas_conteo_zinc_USmt,Metales base,meses_disponibles,Zinc ($/mt),Precio minerales. Metales base. Zinc ($/mt). m...,12.00,Instrumento: Precio
3881,None,2024,precMine_metBas_conteo_zinc_USmt,Metales base,meses_disponibles,Zinc ($/mt),Precio minerales. Metales base. Zinc ($/mt). m...,12.00,Instrumento: Precio
3882,None,2025,precMine_metBas_conteo_zinc_USmt,Metales base,meses_disponibles,Zinc ($/mt),Precio minerales. Metales base. Zinc ($/mt). m...,12.00,Instrumento: Precio
3883,None,2026,precMine_metBas_conteo_zinc_USmt,Metales base,meses_disponibles,Zinc ($/mt),Precio minerales. Metales base. Zinc ($/mt). m...,7.00,Instrumento: Precio

## Preparar salida para STATA

In [80]:
# Los datos son precios internacionales, no corresponden a un municipio en particular.
# Por eso, la columna de municipio no tiene significado en este DF
precios_minerales_salida = precios_minerales_salida.drop(columns=COL_ID_MUNICIPIO)

In [81]:
# Asignar estructura wide para STATA
precios_minerales_salida_STATA = precios_minerales_salida.pivot(
    index=[COL_ANNO],
    columns=COL_NOMBRE_DE_VARIABLE,
    values=COL_VALOR
).reset_index().rename_axis(columns=None)

In [82]:
precios_minerales_salida_STATA

,anno,precMine_carbon_conteo_C_AU_USmt,precMine_carbon_conteo_C_SA_USmt,precMine_carbon_maximo_C_AU_USmt,precMine_carbon_maximo_C_SA_USmt,precMine_carbon_minimo_C_AU_USmt,precMine_carbon_minimo_C_SA_USmt,precMine_carbon_prmdio_C_AU_USmt,precMine_carbon_prmdio_C_SA_USmt,precMine_cobre_conteo_Cu_USmt,precMine_cobre_maximo_Cu_USmt,precMine_cobre_minimo_Cu_USmt,precMine_cobre_prmdio_Cu_USmt,precMine_fertlz_conteo_KCl_USmt,precMine_fertlz_conteo_phsp_USmt,precMine_fertlz_conteo_urea_USmt,precMine_fertlz_maximo_KCl_USmt,precMine_fertlz_maximo_phsp_USmt,precMine_fertlz_maximo_urea_USmt,precMine_fertlz_minimo_KCl_USmt,precMine_fertlz_minimo_phsp_USmt,precMine_fertlz_minimo_urea_USmt,precMine_fertlz_prmdio_KCl_USmt,precMine_fertlz_prmdio_phsp_USmt,precMine_fertlz_prmdio_urea_USmt,precMine_metBas_conteo_Al_USmt,precMine_metBas_conteo_Fe_USmt,precMine_metBas_conteo_Pb_USmt,precMine_metBas_conteo_Sn_USmt,precMine_metBas_conteo_zinc_USmt,precMine_metBas_maximo_Al_USmt,precMine_metBas_maximo_Fe_USmt,precMine_metBas_maximo_Pb_USmt,precMine_metBas_maximo_Sn_USmt,precMine_metBas_maximo_zinc_USmt,precMine_metBas_minimo_Al_USmt,precMine_metBas_minimo_Fe_USmt,precMine_metBas_minimo_Pb_USmt,precMine_metBas_minimo_Sn_USmt,precMine_metBas_minimo_zinc_USmt,precMine_metBas_prmdio_Al_USmt,precMine_metBas_prmdio_Fe_USmt,precMine_metBas_prmdio_Pb_USmt,precMine_metBas_prmdio_Sn_USmt,precMine_metBas_prmdio_zinc_USmt,precMine_niquel_conteo_Ni_USmt,precMine_niquel_maximo_Ni_USmt,precMine_niquel_minimo_Ni_USmt,precMine_niquel_prmdio_Ni_USmt,precMine_oPreci_conteo_Ag_USoz,precMine_oPreci_conteo_plat_USoz,precMine_oPreci_maximo_Ag_USoz,precMine_oPreci_maximo_plat_USoz,precMine_oPreci_minimo_Ag_USoz,precMine_oPreci_minimo_plat_USoz,precMine_oPreci_prmdio_Ag_USoz,precMine_oPreci_prmdio_plat_USoz,precMine_oro_conteo_oro_USoz,precMine_oro_maximo_oro_USoz,precMine_oro_minimo_oro_USoz,precMine_oro_prmdio_oro_USoz
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,728.00,613.00,678.75,12.00,12.00,12.00,28.50,13.00,42.30,28.50,13.00,42.30,28.50,13.00,42.30,12.00,12.00,12.00,12.00,12.00,511.00,11.40,214.00,"2,249.00",261.00,511.00,11.40,179.00,"2,163.00",228.00,511.00,11.40,198.75,"2,196.83",246.25,12.00,"1,631.00","1,631.00","1,631.00",12.00,12.00,0.90,84.00,0.90,84.00,0.90,84.00,12.00,35.00,35.00,35.00
1,1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,668.00,607.00,633.00,12.00,12.00,12.00,30.00,13.00,42.30,30.00,13.00,42.30,30.00,13.00,42.30,12.00,12.00,12.00,12.00,12.00,511.00,11.00,185.00,"2,668.00",233.00,511.00,11.00,166.00,"2,163.00",192.00,511.00,11.00,177.00,"2,450.00",214.33,12.00,"1,711.00","1,711.00","1,711.00",12.00,12.00,1.00,84.00,0.90,84.00,0.91,84.00,12.00,35.00,35.00,35.00
2,1962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,648.00,635.00,645.42,12.00,12.00,12.00,30.00,11.50,42.30,30.00,11.50,42.30,30.00,11.50,42.30,12.00,12.00,12.00,12.00,12.00,511.00,11.00,167.00,"2,652.00",194.00,496.00,11.00,141.00,"2,350.00",177.00,498.00,11.00,155.33,"2,471.42",186.08,12.00,"1,761.00","1,761.00","1,761.00",12.00,12.00,1.20,84.00,1.00,84.00,1.07,84.00,12.00,35.00,35.00,35.00
3,1963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,650.00,646.00,646.33,12.00,12.00,12.00,30.00,11.50,42.30,30.00,11.50,42.30,30.00,11.50,42.30,12.00,12.00,12.00,12.00,12.00,507.00,11.00,205.00,"2,782.00",261.00,496.00,11.00,149.00,"2,350.00",186.00,498.75,11.00,174.92,"2,507.67",211.50,12.00,"1,742.00","1,741.00","1,741.67",12.00,12.00,1.30,84.00,1.20,79.00,1.29,81.33,12.00,35.00,35.00,35.00
4,1964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.00,"1,400.00",656.00,969.67,12.00,12.00,12.00,32.50,12.50,60.50,32.50,12.50,60.50,32.50,12.50,60.50,12.00,12.00,12.00,12.00,12.00,540.00,10.20,384.00,"4,372.00",385.00,507.00,10.20,218.00,"2,873.00",264.00,525.92,10.20,278.00,"3,412.75",326.50,12.00,"1,742.00","1,741.00","1,741.67",12.00,12.00,1.30,89.00,1.30,88.00,1.30,88.92,12.00,35.00,35.00,35.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,2022,12.00,12.00,430.80,302.00,197.00,168.50,344.91,240.56,12.00,"10,231.00","7,545.00","8,822.25",12.00,12.00,12.00,"1,202.00",320.00,925.00,513.80,172.50,519.40,863.43,266.16,700.03,12.00,12.00,12.00,12.00,12.00,"3,498.00",152.10,"2,380.00","43,983.00","4,360.00","2,225.00",92.60,"1,870.00","19,391.00","2,939.00","2,705.00",121.30,"2,150.50","31,335.33","3,481.25",12.00,"33,924.00","21,482.00","25,833.83",12.00,12.00,25.30,"1,049.00",18.90,869.00,21.78,961.67,12.00,"1,948.00","1,664.00","1,800.75"
63,2023,12.00,12.00,318.00,172.00,126.80,96.80,172.78,119.11,12.00,"9,038.00","7,937.00","8,490.33",12.00,12.00,12.00,508.80,347.50,443.80,311.90,152.50,287.50,383.23,323.82,358.01,12.00,12.00,12.00,12.00,12.00,"2,502.00",137.10,"2,252.00","28,743.00","3,310.00","2,137.00",105.20,"2,027.00","24,000.00","2,375.00","2,255.75",120.59,"2,135.75","25,938.17","2,652.75",12.00,"28,195.00","16,461.00","21,521.17",12.00,12.00,25.00,"1,063.00",21.90,892.00,23.41,966.42,12.00,"2,026.00","1,855.00","1,942.75"
64,2024,12.00,12.00,146.60,106.80,124.20,104.80,136.15,105.77,12.00,"10,139.00","8,305.00","9,142.00",12.00,12.00,12.00,310.00,152.50,374.80,278.10,152.50,284.80,295.11,152.50,338.28,12.00,12.00,12.00,12.00,12.00,"2,596.00",135.80,"2,221.00","32,978.00","3,106.00","2,179.00",92.80,"1,988.00","25,100.00","2,360.00","2,419.08",109.41,"2,069.42","30,066.33","2,775.75",12.00,"19,587.00","15,445.00","16,814.00",12.00,12.00,32.40,"1,015.00",22.70,894.00,28.28,955.25,12.00,"2,690.00","2,023.00","2,387.58"
65,2025,12.00,12.00,118.60,103.30,98.60,90.90,108.39,94.89,12.00,"11,785.00","8,991.00","9,947.42",12.00,12.00,12.00,363.10,152.50,507.70,302.00,152.50,380.50,347.52,152.50,422.66,12.00,12.00,12.00,12.00,12.00,"2,876.00",105.10,"2,033.00","41,220.00","3,177.00","2,372.00",92.30,"1,903.00","29,612.00","2,622.00","2,631.67",100.18,"1,962.25","34,058.83","2,867.58",12.00,"16,066.00","14,671.00","15,162.17",12.00,12.00,62.30,"1,893.00",30.40,949.00,39.80,"1,278.33",12.00,"4,309.00","2,710.00","3,441.50"
66,2026,7.00,7.00,138.60,96.30,109.80,90.60,129.29,94.09,7.00,"13,552.00","12,529.00","13,154.43",7.00,7.00,7.00,405.00,170.00,856.90,366.00,152.50,400.00,389.20,155.63,584.79,7.00,7.00,7.00,7.00,7.00,"3,666.00",108.60,"1,995.00","53,563.00","3,599.00","3,065.00",98.20,"1,842.00","47,324.00","3,182.00","3,349.43",103.21,"1,928.43","50,561.86","3,386.14",7.00,"18,806.00","16,651.00","17,575.00",7.00,7.00,92.10,"2,434.00",58.80,"1,622.00",75.90,"1,998.71",7.00,"5,020.00","4,073.00","4,605.43"

## Exportar archivos

In [87]:
# Exportar ambos archivos
nombre_salida = 'e3000_precios_minerales'

precios_minerales_salida.to_parquet(DATA/f'intermediate/{nombre_salida}.parquet',
    index=False)
precios_minerales_salida_STATA.to_stata(DATA/f'intermediate/{nombre_salida}.dta',
    write_index=False)